name: odoo_client
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  uuid: ^2.0.1
  http: ^0.13.0
  shared_preferences: ^0.5.6
  flutter_easyloading: ^2.2.2
  sprintf: ^4.0.2
  url_launcher: ^6.0.2
  flutter_tindercard: ^0.2.0
  mobx:
  flutter_mobx:
  get_it:
  image_picker: ^0.7.4
  latlng: ^0.0.2
  analyzer:
  intl:
  location: ^4.1.1
  open_settings: ^2.0.1
  data_connection_checker: ^0.3.4
  onesignal_flutter: ^2.0.0
  google_maps_flutter: ^2.0.3
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  firebase_core:
  firebase_messaging: ^10.0.4
  get_version: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen:
  flutter_native_splash: ^0.3.2
  flutter_launcher_icons: ^0.8.1

flutter_native_splash:
  color: '#F7F7F7'
  ios: true
  image: assets/splash.jpeg

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
